version: "3"


services:
  postgres:
    image: postgres:13.14-alpine3.19
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  fastapi:
    build: ./
    command: sh -c "echo 'hello' && uvicorn app:app --host 0.0.0.0 --reload"
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - postgres

volumes:
  postgres_volume:
