"""Database creation

Revision ID: 4413e47117be
Revises: 
Create Date: 2024-03-12 10:07:21.208451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4413e47117be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('closing_status', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('shift_task', sa.String(), nullable=False),
    sa.Column('work_center', sa.String(), nullable=False),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('team_number', sa.String(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('product_code_ekn', sa.String(), nullable=False),
    sa.Column('id_rc', sa.String(), nullable=False),
    sa.Column('datetime_begin', sa.DateTime(), nullable=False),
    sa.Column('datetime_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number', 'batch_date', name='butch_num_and_date_uniq'),
    sa.UniqueConstraint('id')
    )
    op.create_table('code_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_product', sa.String(), nullable=True),
    sa.Column('is_aggregated', sa.Boolean(), nullable=True),
    sa.Column('aggregated_at', sa.DateTime(), nullable=True),
    sa.Column('shift_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shift_task_id'], ['shift_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_product'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_product')
    op.drop_table('shift_task')
    # ### end Alembic commands ###
