"""first

Revision ID: 81bfad6fb751
Revises: 4be02905e2c8
Create Date: 2024-03-11 19:27:29.615729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bfad6fb751'
down_revision: Union[str, None] = '4be02905e2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('closing_status', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('shift_task', sa.String(), nullable=False),
    sa.Column('work_center', sa.String(), nullable=False),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('team_number', sa.String(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('product_code_ekn', sa.String(), nullable=False),
    sa.Column('id_rc', sa.String(), nullable=False),
    sa.Column('datetime_begin', sa.DateTime(), nullable=False),
    sa.Column('datetime_end', sa.DateTime(), nullable=False),
    sa.Column('code_product', sa.String(), nullable=True),
    sa.Column('is_aggregated', sa.Boolean(), nullable=True),
    sa.Column('aggregated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_product'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_task')
    # ### end Alembic commands ###
