"""update

Revision ID: 976594e6ae88
Revises: 4413e47117be
Create Date: 2024-03-12 10:18:51.607046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976594e6ae88'
down_revision: Union[str, None] = '4413e47117be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'code_product', ['id'])
    op.create_unique_constraint(None, 'shift_task', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift_task', type_='unique')
    op.drop_constraint(None, 'code_product', type_='unique')
    # ### end Alembic commands ###
